// import LanguageTools from './LanguageTools';
import LanguageTools from 'miot/ui/LocalizedStrings'
import IntlMessageFormat from 'intl-messageformat';
import 'intl';
import 'intl/locale-data/jsonp/en.js';
import 'intl/locale-data/jsonp/zh-Hans.js';
import 'intl/locale-data/jsonp/zh-Hant.js';
import 'intl/locale-data/jsonp/ko-KR.js';


export const strings = {
  'en': {

    //phlips
    addScenes: "Click the add scene button",
    wantscenes: 'Bookmark the custom scenes you want',
    customScenes: "Custom scenes",
    selected: 'Selected',
    item: 'item',
    adjust: 'Adjust',
    guideTip1: "Tap BULB to Turn On/OFF",
    guideTip2: "Swipe Up/Down to Set Brightness",
    guideTip3: "Swipe Left/Right to Set Color Temperature",
    powerOff: "OFF",
    lumStr: "BRI",
    cctStr: "CCT",
    lampOn: 'ON',
    lampOff: 'OFF',
    midNightScene: "Midnight Scene",
    controlStr: "Dimming",
    sceneStr: "Scene",
    model: 'Model',
    delayStr: "Delay Off",
    thStr: "Temp & Hum",
    saveNameTip: "Please enter a name.",
    defaultSceneStr: "Scene",
    conformStr: "Confirm",
    cancelStr: "Cancel",
    failNameTipStr1: "The entered name is too long, please enter a new one.",
    failNameTipStr2: "The entered name is existed, please enter a new one.",
    failNameTipStr3: "The scene is existed, please try again.",
    failNameTipStr4: "The number of scenes is out of limitation.",
    succNameTipStr: "Save successfully",
    failNameTipStr5: "Failed to save",
    // brightness:"Bright",
    brightness: "Teens Study",
    // tv:"TV",
    tv: 'Screen Reading',
    // warm:"Warm",
    warm: 'Concentration',
    midNight: "Focus on learning",
    savedStr: "Favourites",
    warStr: "Warning",
    deleteTipStr: "Please make sure to delete this scene.",
    delayTipStr1: "Swipe button to set delay time",
    delayTipStr2: "Tap to cancel",
    delayTipStr3: "Release to Start",
    delayTipStr4: "The maximum delay time is 6 hours",
    failDelayTipStr: "Please set when the light is turned on.",
    thfailStr: "Please bind the remote controller.",
    tempStr: "Temp",
    humStr: "Hum",
    dayStr: "D",
    weekStr: "W",
    monStr: "Mon.",
    tueStr: "Tue.",
    wedStr: "Wed.",
    thuStr: "Thur.",
    friStr: "Fri.",
    satStr: "Sat.",
    sunStr: "Sun.",
    monthStr: "M",
    settings: "Settings",
    stripSetting: "Lamp Settings",
    autoStr: "Automation",
    generalSetting: "General Settings",
    usingHelp: "Help",
    modifyName: "Rename Device",
    deviceShare: "Share Device",
    checkfw: "Check for Updates",
    unbindStr: "Disconnect",
    feedback: "Feedback",
    snlStr: "Smart Midnight Light",
    snlStrDetail: "Auto turn on ceiling to midnight scene during 23:00-6:00 (power off not support)",
    autoCCT: "Auto CCT",
    autoCCTDet: "Auto Adjust Color Temperature with current time",
    autoSwitch: "Auto On/Off",
    wallSwitchTBri: "Adjust Scenes with Wall Switch",
    wallSwitchTBri2: "Adjust Scenes",
    controller: "Remote Controller",
    bandNearSwitch: "Auto On/Off when Mi Band is Nearby",
    timer: "Schedule power on/off",
    bandNearSwitch2: "Auto On/Off",
    sleepTOff1: "Auto Power Off with Mi Band when asleep",
    sleepTOff2: "Auto Power Off",
    timerSwitch: "On/Off timer",
    bandFuncOn: "Enable Function",
    bandFuncOnDetail: "Turn on the ceiling when Mi Band is nearby. \nTurn off the ceiling when it is far away.",
    advancedSetting: "Advanced Setting",
    bandDistanceStr: "Distance Between Ceiling and MiBand",
    nearStr: "Near",
    farStr: "Far",
    bandTimerSetting1: "Set the Effective Time",
    bandTimerSetting2: "Effective Time",
    bandTimerSetting3: "Set the Effective Time",
    saveBtn: "Save",
    bandTips1: "1. Please open BLE broadcast function in MI FIT application",
    bandTips3: "2. Take the band near the ceiling (3 meters)",
    bandTips2: "Searching nearby band...",
    bandTips4: "No bands found, please refer to the above Guide, and press 'Refresh' button",
    selectBandTip: "Please select a Mi Band",
    bandStr: "Mi Band",
    refreshStr: "Refresh",
    bandFuncOnDetail_sleep: "Auto turn off the ceiling when Mi Band detected you are asleep.",
    isLoading: "Loading...",
    wallSwitchDetail: "Switch scenes when turn on the light within 3 seconds right after turn it off by switch on the wall",
    wallSwitchTip: "Please select scences",
    switchGear: "Wall Switch setting",
    switchGearTip: "Please select the scenes, only 3 scenes",
    saveStr: "Save",
    savingStr: "Saving...",
    saveFailStr: "Failed to save result",
    failSaveStr: "Please select three scences",
    getControlStr: "Receiving the information from remote controller...",
    connectedStr: "Connected",
    unconnectedStr: "Not Connected",
    controlNum: "Remote Controller No.",
    unbindControl: "Delete Remote Controller",
    unbindTips: "Please make sure to remove this remote controller",
    bindTips: "Tap the button below to add remote controller",
    bindcontrol: "Add Remote Controller",
    controlOperStr1: "Keep the remote controller near the ceiling lamp, and long press",
    controlOperStr2: "and",
    controlOperStr3: "for 3s，the indicator of remote controller  will blinking . When the indicator litting , said add successfully.",
    automation: "Automation",
    setCustomStatus: "Switch to a Specified Scene",
    darkStr: "Dark",
    brightStr: "Bright",
    warmStr: "Warm",
    coldStr: "Clod",
    setting: "setting",
    featureSetting: "Shortcut settings",
    commonSetting: "Common settings",
    deviceName: "Device name",
    locationManagement: "Locations",
    shareDevice: "Share device",
    ifttt: "Automation",
    firmwareUpgrate: "Check for firmware updates",
    moreSetting: "Additional settings",
    addToDesktop: "Add to Home screen",
    resetDevice: "Remove device",
    deviceSetting: "Device settings",
    help: "Help",
    BleGateway: "BLE gateway",
    auto: 'Automation',
    licenseVersion: 'web/license-en.html',
    policyVersion: 'web/policy-en.html',
    licenseAndPolicy: "User Agreement & Privacy Policy",
    failCommon: 'Failed',
    licenseTitle: 'User Agreement',
    privacyTitle: 'Privacy Policy',
    attention: 'Attention',
    deviceOffLine: 'Device is offline.',
    securitySetting: 'Security Setting',
    deviceZone: 'Device Zone',
    network: 'NetWork Info',
    signalIntensity: 'WIFI Signal',
    deviceIp: "Device Ip",
    deviceMac: "MAC",
    workingModel: 'Working Model',
    lanMode: 'LAN NetWork',
    netError: 'Net Error',
    wifiName: 'Wi-Fi Name',
    wifiSignal: 'Wi-Fi Signal Strength',
    rssi: 'RSSI',
    currentMode: 'Current Mode',
    ipAddress: 'IP Address',
    macAddress: 'MAC Address',
    getting: 'One moment...',
    remoteConnection: 'Remote connection',
    netWorkConnection: 'Network connection',
    delete: 'Delete',
    used: 'Used',
    use: 'Use',
    nameIsNull: 'Name can`t null '
  },
  'zh': {

    //philips
    addScenes: '点击添加场景按钮',
    wantscenes: '收藏你想要的自定义场景',
    customScenes: '自定义场景',
    selected: '已选',
    item: '项',
    use: '使用',
    delete: '删除',
    adjust: '调节',
    used: '已使用',
    guideTip1: "轻点灯泡开关",
    guideTip2: "上下调亮度",
    guideTip3: "左右调色温",
    powerOff: "已关闭",
    lumStr: "亮度",
    cctStr: "色温",
    lampOn: '开灯',
    lampOff: '关灯',
    midNightScene: "起夜情景",
    controlStr: "调光",
    sceneStr: "情景",
    model: '模式',
    delayStr: "延时关灯",
    thStr: "温湿度",
    saveNameTip: "请输入名称",
    defaultSceneStr: "Scene",
    conformStr: "确定",
    cancelStr: "取消",
    nameIsNull: '名称不能为空',
    failNameTipStr1: "您输入的名称过长，请重新添加保存",
    failNameTipStr2: "您输入的名称已存在，请输入新的名称保存",
    failNameTipStr3: "您保存的状态已存在，请重新添加保存",
    failNameTipStr4: "您保存的状态已到达上限",
    succNameTipStr: "收藏成功",
    failNameTipStr5: "收藏失败",
    // brightness:"明亮",
    brightness: "儿童读写",
    // tv:"电视",
    tv: '屏幕阅读',
    // warm:"温馨",
    warm: "高效工作",
    // midNight:"起夜",
    midNight: "专注学习",
    savedStr: "已收藏",
    warStr: "提示",
    deleteTipStr: "请确认删除收藏项的操作",
    delayTipStr1: "滑动上部按钮调节时间",
    delayTipStr2: "点击取消执行",
    delayTipStr3: "松手执行延时",
    delayTipStr4: "设置延时关灯最大时间为6小时",
    failDelayTipStr: "请在开灯时操作",
    thfailStr: "您还没绑定遥控器",
    tempStr: "温度",
    humStr: "湿度",
    dayStr: "天",
    weekStr: "周",
    monStr: "星期一",
    tueStr: "星期二",
    wedStr: "星期三",
    thuStr: "星期四",
    friStr: "星期五",
    satStr: "星期六",
    sunStr: "星期日",
    monthStr: "月",
    settings: "设置",
    stripSetting: "台灯设置",
    autoStr: "自动化",
    generalSetting: "通用设置",
    usingHelp: "使用帮助",
    modifyName: "重命名",
    deviceShare: "设备共享",
    checkfw: "检查固件升级",
    unbindStr: "解除连接",
    feedback: "反馈",
    snlStr: "智能起夜灯",
    snlStrDetail: "夜里(23:00-6:00)开灯时，自动调至起夜情景(不支持断电后开灯)",
    autoCCT: "自动调节色温",
    autoCCTDet: "随时间段自动调节色温",
    autoSwitch: "自动开关",
    wallSwitchTBri: "墙壁开关切换情景",
    wallSwitchTBri2: "墙壁开关切换情景",
    controller: "遥控器",
    bandNearSwitch: "小米手环靠近开灯离开关灯(实验室)",
    bandNearSwitch2: "小米手环靠近开灯离开关灯",
    sleepTOff1: "睡着自动关灯(需佩戴手环)",
    sleepTOff2: "睡着自动关灯",
    timerSwitch: "定时开关",
    timer: "定时开关",
    bandFuncOn: "开启功能",
    bandFuncOnDetail: "手环靠近吸顶灯自动开灯，离开后自动关灯",
    advancedSetting: "高级设置",
    bandDistanceStr: "手环与灯距离",
    nearStr: "近",
    farStr: "远",
    BleGateway: "蓝牙网关",
    bandTimerSetting1: "设置生效时间",
    bandTimerSetting2: "生效时间段",
    bandTimerSetting3: "设置生效时间段",
    saveBtn: "保存",
    bandTips1: "1、需在小米运动中开启手环的蓝牙广播",
    bandTips3: "2、将手环靠近吸顶灯(3米内)",
    bandTips2: "正在搜索附近手环信息...",
    bandTips4: "未发现可用手环，请参照上方引导并点击刷新按钮",
    selectBandTip: "请选择手环",
    bandStr: "手环",
    refreshStr: "刷新",
    bandFuncOnDetail_sleep: "小米手环探测到睡着后自动关灯",
    isLoading: "正在加载...",
    wallSwitchDetail: "通过墙壁开关关灯后3秒内再次开灯后切换情景",
    wallSwitchTip: "请选择情景亮度",
    switchGear: "切换档位设置",
    switchGearTip: "请选择情景亮度，只能选3个",
    saveStr: "保存",
    savingStr: "正在保存...",
    saveFailStr: "保存失敗",
    failSaveStr: "只能选择3个情景亮度",
    getControlStr: "正在获取遥控器信息...",
    connectedStr: "已连接",
    unconnectedStr: "未连接",
    controlNum: "遥控器编号",
    unbindControl: "删除配对",
    unbindTips: "请确认删除绑定的遥控器",
    bindTips: "点击下方按钮，添加遥控器",
    bindcontrol: "添加遥控器",
    controlOperStr1: "将遥控器靠近吸顶灯，长按",
    controlOperStr2: "以及",
    controlOperStr3: "键3秒，遥控器指示灯闪烁。指示灯常亮，则表示添加成功。",
    automation: "自动化",
    setCustomStatus: "调至指定状态",
    darkStr: "暗",
    brightStr: "亮",
    warmStr: "暖",
    coldStr: "冷",
    setting: "设置",
    featureSetting: "功能设置",
    commonSetting: "通用设置",
    deviceName: "设备名称",
    locationManagement: "位置管理",
    shareDevice: "设备共享",
    ifttt: "智能",
    firmwareUpgrate: "检查固件升级",
    moreSetting: "更多设置",
    addToDesktop: "添加到桌面",
    resetDevice: "删除设备",
    deviceSetting: "设备设置",
    help: "使用帮助",
    auto: '智能',
    licenseVersion: 'web/license.html',
    policyVersion: 'web/policy.html',
    licenseAndPolicy: "使用条款和隐私政策",
    failCommon: '失败',
    licenseTitle: '使用条款',
    privacyTitle: '隐私政策',
    attention: '提示',
    deviceOffLine: '设备离线',
    securitySetting: '安全设置',
    deviceZone: '设备时区',
    network: "网络信息",
    signalIntensity: 'WIFI强度',
    deviceIp: "IP地址",
    deviceMac: "MAC地址",
    workingModel: '当前模式',
    lanMode: '局域网连接',
    netError: '连接错误',
    wifiName: 'WIFI名称',
    wifiSignal: 'WIFI强度',
    rssi: 'RSSI',
    currentMode: '当前模式',
    ipAddress: 'IP地址',
    macAddress: 'MAC地址',
    getting: '正在获取',
    remoteConnection: '远程连接',
    netWorkConnection: '局域网连接 ',

  },
  'zh-tw': {
    //philips
    customScenes: "自定义场景",
    guideTip1: "輕點燈泡開關",
    guideTip2: "上下調亮度",
    guideTip3: "左右調色溫",
    powerOff: "已關閉",
    lumStr: "亮度",
    cctStr: "色溫",
    midNightScene: "起夜情景",
    controlStr: "調光",
    sceneStr: "情景",
    delayStr: "延時關",
    thStr: "溫濕度",
    saveNameTip: "請輸入名稱",
    defaultSceneStr: "Scene",
    conformStr: "確定",
    cancelStr: "取消",
    failNameTipStr1: "您輸入的名稱過長，請重新添加儲存",
    failNameTipStr2: "您輸入的名稱已存在，請输入新的名稱儲存",
    failNameTipStr3: "您儲存的狀態已存在，請重新添加儲存",
    failNameTipStr4: "您儲存的狀態已到達上限",
    succNameTipStr: "收藏成功",
    failNameTipStr5: "收藏失敗",
    BleGateway: "藍牙網關",
    // brightness:"明亮",
    brightness: "儿童读写",
    // tv:"電視",
    tv: '屏幕阅读',
    // warm:"溫馨",
    warm: "高效工作",
    // midNight:"夜起",
    midNight: "专注学习",
    savedStr: "已收藏",
    warStr: "提示",
    deleteTipStr: "請確認刪除收藏項的操作",
    delayTipStr1: "滑動上部按鈕調節時間",
    delayTipStr2: "點擊取消執行",
    delayTipStr3: "鬆手執行延時",
    delayTipStr4: "設置延時關燈最大時間為6小時",
    failDelayTipStr: "請在開燈時操作",
    thfailStr: "您还没绑定遥控器",
    tempStr: "溫度",
    humStr: "濕度",
    dayStr: "天",
    weekStr: "週",
    monStr: "星期一",
    tueStr: "星期二",
    wedStr: "星期三",
    thuStr: "星期四",
    friStr: "星期五",
    satStr: "星期六",
    sunStr: "星期日",
    monthStr: "月",
    settings: "設定",
    stripSetting: "台灯設定",
    autoStr: "自動化",
    generalSetting: "通用設置",
    usingHelp: "使用幫助",
    modifyName: "修改設備名稱",
    deviceShare: "設備共享",
    checkfw: "檢查固件升級",
    unbindStr: "解除連接",
    feedback: "反饋",
    snlStr: "智能夜起燈",
    snlStrDetail: "夜晚(23:00-6:00)開燈時，自動調至起夜情景(不支持斷電後開燈)",
    autoCCT: "自動調節色溫",
    autoCCTDet: "隨時間段自動調節色溫",
    autoSwitch: "自動開關",
    wallSwitchTBri: "牆壁開關切換情景",
    wallSwitchTBri2: "牆壁開關切換情景",
    controller: "遙控器",
    bandNearSwitch: "小米手環靠近開燈離開關燈(實驗室)",
    bandNearSwitch2: "小米手環靠近開燈離開關燈",
    sleepTOff1: "睡著自動關燈(需佩戴手環)",
    sleepTOff2: "睡著自動關燈",
    timerSwitch: "定時開關",
    timer: "定時開關",
    bandFuncOn: "開啟功能",
    bandFuncOnDetail: "手環靠近吸頂燈自動開燈，離開後自動關燈",
    advancedSetting: "高級設定",
    bandDistanceStr: "手環與燈距離",
    nearStr: "近",
    farStr: "遠",
    bandTimerSetting1: "設定生效時間",
    bandTimerSetting2: "生效時間段",
    bandTimerSetting3: "設定生效時間段",
    saveBtn: "保存",
    bandTips1: "1、需在小米運動的\"智玩\"中開啟手環的\"藍牙廣播\"查看詳情",
    bandTips3: "2、將手環靠近吸頂燈(3米內)",
    bandTips2: "正在搜索附近手環信息...",
    bandTips4: "未發現可用手環，請參照上方引導",
    selectBandTip: "請選擇手環",
    bandStr: "手環",
    refreshStr: "刷新",
    bandFuncOnDetail_sleep: "小米手環探測到睡著後自動關燈",
    isLoading: "正在加載...",
    wallSwitchDetail: "通過牆壁開關關燈後3秒內再次開燈後切換情景",
    wallSwitchTip: "請選擇情景亮度",
    switchGear: "切換檔位設置",
    switchGearTip: "請選擇情景亮度，只能選3個",
    saveStr: "儲存",
    savingStr: "正在儲存...",
    saveFailStr: "保存失敗",
    failSaveStr: "只能選擇3個情景亮度",
    getControlStr: "正在獲取遙控器訊息...",
    connectedStr: "已連接",
    unconnectedStr: "未連接",
    controlNum: "遙控器編號",
    unbindControl: "刪除配對",
    unbindTips: "請確認刪除綁定的遙控器",
    bindTips: "點擊下方按鈕，添加遙控器",
    bindcontrol: "添加遙控器",
    controlOperStr1: "將遙控器靠近吸頂燈，長按",
    controlOperStr2: "以及",
    controlOperStr3: "鍵3秒，遙控器指示燈閃爍。指示燈常亮，則表示添加成功。",
    automation: "自動化",
    setCustomStatus: "調至指定狀態",
    darkStr: "暗",
    brightStr: "亮",
    warmStr: "暖",
    coldStr: "冷",
    setting: "設置",
    featureSetting: "功能設定",
    commonSetting: "一般設定",
    deviceName: "裝置名稱",
    locationManagement: "位置管理",
    shareDevice: "裝置共用",
    ifttt: "智慧",
    firmwareUpgrate: "檢查韌體更新",
    moreSetting: "更多設定",
    addToDesktop: "新增到桌面",
    resetDevice: "刪除裝置",
    deviceSetting: "裝置設置",
    help: "使用幫助",
    auto: '智慧',
    licenseVersion: 'web/license-zh-Hant.html',
    policyVersion: 'web/policy-zh-Hant.html',
    licenseAndPolicy: "用戶協議和隱私政策",
    failCommon: '失敗',
    licenseTitle: '使用條款',
    privacyTitle: '隱私政策',
    attention: '提示',
    deviceOffLine: '設備離綫',
    securitySetting: '安全設置',
    deviceZone: '設備時區',
    network: "網絡信息",
    signalIntensity: 'WIFI强度',
    deviceIp: "IP地址",
    deviceMac: "MAC地址",
    workingModel: '當前模式',
    lanMode: '局域網鏈接',
    netError: '鏈接錯誤',
    wifiName: 'WIFI名稱',
    wifiSignal: 'WiFi強度',
    rssi: 'RSSI',
    currentMode: '目前模式',
    ipAddress: 'IP位址',
    macAddress: 'MAC位址',
    getting: '正在取得',
    remoteConnection: '遠端連線',
    netWorkConnection: '區域網連接 ',

  },
  'zh-hk': {
    customScenes: "Custom scenes",
    guideTip1: "輕點燈泡開關",
    guideTip2: "上下調亮度",
    guideTip3: "左右調色溫",
    powerOff: "已關閉",
    lumStr: "亮度",
    cctStr: "色溫",
    midNightScene: "起夜情景",
    controlStr: "調光",
    sceneStr: "情景",
    delayStr: "延時關",
    BleGateway: "藍牙網關",
    thStr: "溫濕度",
    saveNameTip: "請輸入名稱",
    defaultSceneStr: "Scene",
    conformStr: "確定",
    cancelStr: "取消",
    failNameTipStr1: "您輸入的名稱過長，請重新添加儲存",
    failNameTipStr2: "您輸入的名稱已存在，請输入新的名稱儲存",
    failNameTipStr3: "您儲存的狀態已存在，請重新添加儲存",
    failNameTipStr4: "您儲存的狀態已到達上限",
    succNameTipStr: "收藏成功",
    failNameTipStr5: "收藏失敗",
    // brightness:"明亮",
    brightness: '儿童读写',
    // tv:"電視",
    tv: '屏幕阅读',
    // warm:"溫馨",
    warm: "高效工作",
    // midNight:"夜起",
    midNight: "专注学习",
    savedStr: "已收藏",
    warStr: "提示",
    deleteTipStr: "請確認刪除收藏項的操作",
    delayTipStr1: "滑動上部按鈕調節時間",
    delayTipStr2: "點擊取消執行",
    delayTipStr3: "鬆手執行延時",
    delayTipStr4: "設置延時關燈最大時間為6小時",
    failDelayTipStr: "請在開燈時操作",
    thfailStr: "您还没绑定遥控器",
    tempStr: "溫度",
    humStr: "濕度",
    dayStr: "天",
    weekStr: "週",
    monStr: "星期一",
    tueStr: "星期二",
    wedStr: "星期三",
    thuStr: "星期四",
    friStr: "星期五",
    satStr: "星期六",
    sunStr: "星期日",
    monthStr: "月",
    settings: "設定",
    stripSetting: "台灯設定",
    autoStr: "自動化",
    generalSetting: "通用設置",
    usingHelp: "使用幫助",
    modifyName: "修改設備名稱",
    deviceShare: "設備共享",
    checkfw: "檢查固件升級",
    unbindStr: "解除連接",
    feedback: "反饋",
    snlStr: "智能夜起燈",
    snlStrDetail: "夜晚(23:00-6:00)開燈時，自動調至起夜情景(不支持斷電後開燈)",
    autoCCT: "自動調節色溫",
    autoCCTDet: "隨時間段自動調節色溫",
    autoSwitch: "自動開關",
    wallSwitchTBri: "牆壁開關切換情景",
    wallSwitchTBri2: "牆壁開關切換情景",
    controller: "遙控器",
    bandNearSwitch: "小米手環靠近開燈離開關燈(實驗室)",
    bandNearSwitch2: "小米手環靠近開燈離開關燈",
    sleepTOff1: "睡著自動關燈(需佩戴手環)",
    sleepTOff2: "睡著自動關燈",
    timerSwitch: "定時開關",
    timer: "定時開關",
    bandFuncOn: "開啟功能",
    bandFuncOnDetail: "手環靠近吸頂燈自動開燈，離開後自動關燈",
    advancedSetting: "高級設定",
    bandDistanceStr: "手環與燈距離",
    nearStr: "近",
    farStr: "遠",
    bandTimerSetting1: "設定生效時間",
    bandTimerSetting2: "生效時間段",
    bandTimerSetting3: "設定生效時間段",
    saveBtn: "保存",
    bandTips1: "1、需在小米運動的\"智玩\"中開啟手環的\"藍牙廣播\"查看詳情",
    bandTips3: "2、將手環靠近吸頂燈(3米內)",
    bandTips2: "正在搜索附近手環信息...",
    bandTips4: "未發現可用手環，請參照上方引導",
    selectBandTip: "請選擇手環",
    bandStr: "手環",
    refreshStr: "刷新",
    bandFuncOnDetail_sleep: "小米手環探測到睡著後自動關燈",
    isLoading: "正在加載...",
    wallSwitchDetail: "通過牆壁開關關燈後3秒內再次開燈後切換情景",
    wallSwitchTip: "請選擇情景亮度",
    switchGear: "切換檔位設置",
    switchGearTip: "請選擇情景亮度，只能選3個",
    saveStr: "儲存",
    savingStr: "正在儲存...",
    saveFailStr: "保存失敗",
    failSaveStr: "只能選擇3個情景亮度",
    getControlStr: "正在獲取遙控器訊息...",
    connectedStr: "已連接",
    unconnectedStr: "未連接",
    controlNum: "遙控器編號",
    unbindControl: "刪除配對",
    unbindTips: "請確認刪除綁定的遙控器",
    bindTips: "點擊下方按鈕，添加遙控器",
    bindcontrol: "添加遙控器",
    controlOperStr1: "將遙控器靠近吸頂燈，長按",
    controlOperStr2: "以及",
    controlOperStr3: "鍵3秒，遙控器指示燈閃爍。指示燈常亮，則表示添加成功。",
    automation: "自動化",
    setCustomStatus: "調至指定狀態",
    darkStr: "暗",
    brightStr: "亮",
    warmStr: "暖",
    coldStr: "冷",
    setting: "設置",
    featureSetting: "功能設定",
    commonSetting: "一般設定",
    deviceName: "裝置名稱",
    locationManagement: "位置管理",
    shareDevice: "裝置共用",
    ifttt: "智慧",
    firmwareUpgrate: "檢查韌體更新",
    moreSetting: "更多設定",
    addToDesktop: "新增到桌面",
    resetDevice: "刪除裝置",
    deviceSetting: "裝置設置",
    help: "使用幫助",
    auto: '智慧',
    licenseVersion: 'web/license-zh-Hant.html',
    policyVersion: 'web/policy-zh-Hant.html',
    licenseAndPolicy: "用戶協議和隱私政策",
    failCommon: '失敗',
    licenseTitle: '使用條款',
    privacyTitle: '隱私政策',
    attention: '提示',
    deviceOffLine: '設備離綫',
    securitySetting: '安全設置',
    deviceZone: '設備時區',
    network: "網絡信息",
    signalIntensity: 'WIFI强度',
    deviceIp: "IP地址",
    deviceMac: "MAC地址",
    workingModel: '當前模式',
    lanMode: '局域網鏈接',
    netError: '鏈接錯誤',
    wifiName: 'WIFI名稱',
    wifiSignal: 'WiFi強度',
    rssi: 'RSSI',
    currentMode: '目前模式',
    ipAddress: 'IP位址',
    macAddress: 'MAC位址',
    getting: '正在取得',
    remoteConnection: '遠端連線',
    netWorkConnection: '區域網連接 ',

  },
  'ko': {
    NUM_PHOTOS: 'You have {numPhotos, plural, ' +
      '=0 {no photos.}' +
      '=1 {one photo.}' +
      'other {# photos.}}',
    featureSetting: '바로가기 설정',
    commonSetting: '일반 설정',
    deviceName: '기기 이름',
    locationManagement: '위치',
    shareDevice: '기기 공유',
    ifttt: '자동화',
    firmwareUpgrate: '펌웨어 업데이트 확인',
    moreSetting: '추가 설정',
    addToDesktop: '홈 화면에 추가',
    resetDevice: '기기 초기화',
    licenseAndPolicy: '이용 약관 & 개인 정보 보호 정책',
  },
};

export const localStrings = new LanguageTools(strings);

export function getString(key, obj = null) {
  if (obj) {
    return new IntlMessageFormat(localStrings[key], localStrings.language).format(obj);
  } else {
    return localStrings[key];
  }
}
